Remove duplicate extern declarations in ui.cpp
Fixed compilation error:
- Removed duplicate declarations of g_displayCurrency, g_usdToTwd, g_fxValid
- These are already declared in app_state.h (included on line 12)
- Resolves conflict: 'float g_usdToTwd' vs 'float& g_usdToTwd'

Error message:
  src/ui.cpp:42:14: error: conflicting declaration 'float g_usdToTwd'
  include/app_state.h:75:15: note: previous declaration as 'float& g_usdToTwd'